export const firebaseCollections = {
  users: "users",
  availabilitySlots: "availabilitySlots",
  messages: "messages",
  conversations: "conversations",
  bookings: "bookings",
  students: "students",
  tutors: "tutors",
  usersProfiles: "usersProfiles",
  reviews: "reviews",
  matchings: "matchings",
  engagedUsers: "engagedUsers",
  stats: "stats",
  profileViews: "profileViews",
  contactInquiries: "contactInquiries",
};
